# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- beta

# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xcode
pool:
  vmImage: 'macOS-10.14'


steps:
- task: AppStoreRelease@1
  inputs:
    authType: 'UserAndPass'
    username: 'ta.anders17@gmail.com'
    password: $(TRANSPORTER_PASSWORD)
    appIdentifier: 'com.taloranderson.sup'
    appType: 'iOS'
    releaseTrack: 'TestFlight'
    shouldSkipSubmission: true
    appSpecificId: '1532550390'
    teamId: '121918681'
    teamName: 'Talor Anderson'
