pr: none
trigger:
  branches:
    include:
      - beta

jobs:
  - job: Functions
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - script: |
          echo "hello world from the beta branch!"
