pr:
- master
triggers: none

jobs:
- job: Functions
  pool:
    vmImage: "ubuntu-16.04"
  steps:
    - template: templates/firebase-deploy.yml
      parameters:
        deploy: false
- job: "iOS"
  pool:
    vmImage: "macOS-10.14"
  steps:
    - script: |
        echo "hello world!"
