# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sup
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'


  target 'supTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'supUITests' do
    # Pods for testing
  end

end
